version: "3"

services:
  minisearch_service:
    build:
      context: ../
      dockerfile: ./build/Dockerfile-minisearch
    image: minisearch_service_docker_image    
    volumes:
      - ../configs/config-docker.toml:/etc/minisearch/config.toml:ro

    restart: on-failure
    ports:
      - "8088:8088"  
    expose:
      - 8088